import type {
  Element,
  HoangDaoStar,
  TrucInfo,
  SolarTerm,
  ThienCan,
  DiaChi,
} from './types';

interface NapAmInfo {
  name: string;
  element: Element;
}

export const THIEN_CAN: ThienCan[] = [
  { index: 0, name: 'Giáp', element: 'moc', yin: false },
  { index: 1, name: 'Ất', element: 'moc', yin: true },
  { index: 2, name: 'Bính', element: 'hoa', yin: false },
  { index: 3, name: 'Đinh', element: 'hoa', yin: true },
  { index: 4, name: 'Mậu', element: 'tho', yin: false },
  { index: 5, name: 'Kỷ', element: 'tho', yin: true },
  { index: 6, name: 'Canh', element: 'kim', yin: false },
  { index: 7, name: 'Tân', element: 'kim', yin: true },
  { index: 8, name: 'Nhâm', element: 'thuy', yin: false },
  { index: 9, name: 'Quý', element: 'thuy', yin: true },
];

export const DIA_CHI: DiaChi[] = [
  { index: 0, name: 'Tý', animal: 'Chuột', element: 'thuy' },
  { index: 1, name: 'Sửu', animal: 'Trâu', element: 'tho' },
  { index: 2, name: 'Dần', animal: 'Hổ', element: 'moc' },
  { index: 3, name: 'Mão', animal: 'Mão', element: 'moc' },
  { index: 4, name: 'Thìn', animal: 'Rồng', element: 'tho' },
  { index: 5, name: 'Tỵ', animal: 'Rắn', element: 'hoa' },
  { index: 6, name: 'Ngọ', animal: 'Ngựa', element: 'hoa' },
  { index: 7, name: 'Mùi', animal: 'Dê', element: 'tho' },
  { index: 8, name: 'Thân', animal: 'Khỉ', element: 'kim' },
  { index: 9, name: 'Dậu', animal: 'Gà', element: 'kim' },
  { index: 10, name: 'Tuất', animal: 'Chó', element: 'tho' },
  { index: 11, name: 'Hợi', animal: 'Heo', element: 'thuy' },
];

export const LUNAR_MONTH_NAMES = [
  'Giêng',
  'Hai',
  'Ba',
  'Tư',
  'Năm',
  'Sáu',
  'Bảy',
  'Tám',
  'Chín',
  'Mười',
  'Một',
  'Chạp',
];

export const HOANG_DAO_STARS: HoangDaoStar[] = [
  { name: 'Thanh Long', type: 'hoangdao', meaning: 'Cát tinh mang lại sự hanh thông' },
  { name: 'Minh Đường', type: 'hoangdao', meaning: 'Sáng suốt, thuận lợi ký kết' },
  { name: 'Thiên Hình', type: 'hacdao', meaning: 'Không thuận cho kiện tụng, tranh chấp' },
  { name: 'Chu Tước', type: 'hacdao', meaning: 'Dễ gặp khẩu thiệt, thị phi' },
  { name: 'Kim Quỹ', type: 'hoangdao', meaning: 'Tài lộc, tốt cho cưới hỏi' },
  { name: 'Thiên Đức', type: 'hoangdao', meaning: 'Phúc đức, tốt cho cầu tài' },
  { name: 'Bạch Hổ', type: 'hacdao', meaning: 'Hung sát, tránh động thổ' },
  { name: 'Ngọc Đường', type: 'hoangdao', meaning: 'Cát tường, tốt cho khai trương' },
  { name: 'Thiên Lao', type: 'hacdao', meaning: 'Trở ngại, dễ gặp ràng buộc pháp lý' },
  { name: 'Huyền Vũ', type: 'hacdao', meaning: 'Hung tinh, tránh đi xa' },
  { name: 'Tư Mệnh', type: 'hoangdao', meaning: 'Bảo hộ, tốt cho mọi việc lớn' },
  { name: 'Câu Trần', type: 'hacdao', meaning: 'Trì trệ, dễ gặp trở ngại' },
];

export const HOUR_STAR_START_TABLE = [0, 2, 4, 6, 8, 10, 0, 2, 4, 6, 8, 10];

export const TRUC_INFO: TrucInfo[] = [
  {
    id: 'kien',
    name: 'Kiến',
    type: 'hacdao',
    goodFor: ['Xuất hành', 'Khai trương nhỏ'],
    badFor: ['Khai trương lớn', 'Động thổ'],
  },
  {
    id: 'tru',
    name: 'Trừ',
    type: 'hoangdao',
    goodFor: ['Trừ tà', 'Tảo mộ'],
    badFor: ['Cưới hỏi'],
  },
  {
    id: 'man',
    name: 'Mãn',
    type: 'hacdao',
    goodFor: ['Thụ lộc'],
    badFor: ['Động thổ', 'Xây dựng'],
  },
  {
    id: 'binh',
    name: 'Bình',
    type: 'hacdao',
    goodFor: ['Việc nhỏ'],
    badFor: ['Ký kết quan trọng'],
  },
  {
    id: 'dinh',
    name: 'Định',
    type: 'hoangdao',
    goodFor: ['Cưới hỏi', 'Ký kết'],
    badFor: ['Tranh chấp'],
  },
  {
    id: 'chap',
    name: 'Chấp',
    type: 'hoangdao',
    goodFor: ['Xây dựng', 'Gieo trồng'],
    badFor: ['Chuyển nhà'],
  },
  {
    id: 'pha',
    name: 'Phá',
    type: 'hacdao',
    goodFor: ['Phá dỡ'],
    badFor: ['Mọi việc quan trọng'],
  },
  {
    id: 'nguy',
    name: 'Nguy',
    type: 'hacdao',
    goodFor: ['Cúng tế'],
    badFor: ['Khai trương', 'Cưới hỏi'],
  },
  {
    id: 'thanh',
    name: 'Thành',
    type: 'hoangdao',
    goodFor: ['Hoàn thiện công việc', 'Động thổ'],
    badFor: ['Kiện tụng'],
  },
  {
    id: 'thu',
    name: 'Thu',
    type: 'hacdao',
    goodFor: ['Thu hoạch'],
    badFor: ['Xây dựng'],
  },
  {
    id: 'khai',
    name: 'Khai',
    type: 'hoangdao',
    goodFor: ['Khai trương', 'Mở kho'],
    badFor: ['An táng'],
  },
  {
    id: 'be',
    name: 'Bế',
    type: 'hacdao',
    goodFor: ['Đóng cửa kho'],
    badFor: ['Khởi công', 'Cưới hỏi'],
  },
];

export const SOLAR_TERMS: SolarTerm[] = [
  { index: 0, name: 'Tiểu Hàn', chineseName: '小寒', date: { year: 0, month: 1, day: 5 }, description: 'Thời tiết se lạnh, chuẩn bị cho Đại Hàn.' },
  { index: 1, name: 'Đại Hàn', chineseName: '大寒', date: { year: 0, month: 1, day: 20 }, description: 'Giai đoạn lạnh nhất trong năm.' },
  { index: 2, name: 'Lập Xuân', chineseName: '立春', date: { year: 0, month: 2, day: 4 }, description: 'Bắt đầu mùa xuân.' },
  { index: 3, name: 'Vũ Thủy', chineseName: '雨水', date: { year: 0, month: 2, day: 19 }, description: 'Mưa phùn xuất hiện, báo hiệu vụ mùa mới.' },
  { index: 4, name: 'Kinh Trập', chineseName: '惊蛰', date: { year: 0, month: 3, day: 5 }, description: 'Côn trùng tỉnh giấc sau mùa đông.' },
  { index: 5, name: 'Xuân Phân', chineseName: '春分', date: { year: 0, month: 3, day: 20 }, description: 'Ngày đêm bằng nhau.' },
  { index: 6, name: 'Thanh Minh', chineseName: '清明', date: { year: 0, month: 4, day: 4 }, description: 'Tiết trời trong sáng, tảo mộ.' },
  { index: 7, name: 'Cốc Vũ', chineseName: '谷雨', date: { year: 0, month: 4, day: 20 }, description: 'Mưa rào nuôi dưỡng mùa màng.' },
  { index: 8, name: 'Lập Hạ', chineseName: '立夏', date: { year: 0, month: 5, day: 5 }, description: 'Bắt đầu mùa hạ.' },
  { index: 9, name: 'Tiểu Mãn', chineseName: '小满', date: { year: 0, month: 5, day: 21 }, description: 'Lúa bắt đầu chắc hạt.' },
  { index: 10, name: 'Mang Chủng', chineseName: '芒种', date: { year: 0, month: 6, day: 6 }, description: 'Thời điểm gieo trồng các loại lúa có màng.' },
  { index: 11, name: 'Hạ Chí', chineseName: '夏至', date: { year: 0, month: 6, day: 21 }, description: 'Ngày dài nhất trong năm.' },
  { index: 12, name: 'Tiểu Thử', chineseName: '小暑', date: { year: 0, month: 7, day: 7 }, description: 'Bắt đầu nóng nực.' },
  { index: 13, name: 'Đại Thử', chineseName: '大暑', date: { year: 0, month: 7, day: 22 }, description: 'Thời điểm nóng nhất trong năm.' },
  { index: 14, name: 'Lập Thu', chineseName: '立秋', date: { year: 0, month: 8, day: 7 }, description: 'Bắt đầu mùa thu.' },
  { index: 15, name: 'Xử Thử', chineseName: '处暑', date: { year: 0, month: 8, day: 23 }, description: 'Nhiệt độ bắt đầu giảm.' },
  { index: 16, name: 'Bạch Lộ', chineseName: '白露', date: { year: 0, month: 9, day: 7 }, description: 'Sương trắng xuất hiện.' },
  { index: 17, name: 'Thu Phân', chineseName: '秋分', date: { year: 0, month: 9, day: 23 }, description: 'Ngày đêm bằng nhau lần hai.' },
  { index: 18, name: 'Hàn Lộ', chineseName: '寒露', date: { year: 0, month: 10, day: 8 }, description: 'Không khí chuyển lạnh.' },
  { index: 19, name: 'Sương Giáng', chineseName: '霜降', date: { year: 0, month: 10, day: 23 }, description: 'Sương mù, sương muối xuất hiện.' },
  { index: 20, name: 'Lập Đông', chineseName: '立冬', date: { year: 0, month: 11, day: 7 }, description: 'Bắt đầu mùa đông.' },
  { index: 21, name: 'Tiểu Tuyết', chineseName: '小雪', date: { year: 0, month: 11, day: 22 }, description: 'Bắt đầu có tuyết ở vùng ôn đới.' },
  { index: 22, name: 'Đại Tuyết', chineseName: '大雪', date: { year: 0, month: 12, day: 7 }, description: 'Tuyết rơi dày đặc.' },
  { index: 23, name: 'Đông Chí', chineseName: '冬至', date: { year: 0, month: 12, day: 21 }, description: 'Ngày ngắn nhất trong năm.' },
];

export const NAP_AM: NapAmInfo[] = [
  { name: 'Hải Trung Kim', element: 'kim' },
  { name: 'Lô Trung Hỏa', element: 'hoa' },
  { name: 'Đại Lâm Mộc', element: 'moc' },
  { name: 'Lộ Bàng Thổ', element: 'tho' },
  { name: 'Kiếm Phong Kim', element: 'kim' },
  { name: 'Sơn Đầu Hỏa', element: 'hoa' },
  { name: 'Giản Hạ Thủy', element: 'thuy' },
  { name: 'Thành Đầu Thổ', element: 'tho' },
  { name: 'Bạch Lạp Kim', element: 'kim' },
  { name: 'Dương Liễu Mộc', element: 'moc' },
  { name: 'Tuyền Trung Thủy', element: 'thuy' },
  { name: 'Ốc Thượng Thổ', element: 'tho' },
  { name: 'Tích Lịch Hỏa', element: 'hoa' },
  { name: 'Tùng Bách Mộc', element: 'moc' },
  { name: 'Trường Lưu Thủy', element: 'thuy' },
  { name: 'Sa Trung Kim', element: 'kim' },
  { name: 'Sơn Hạ Hỏa', element: 'hoa' },
  { name: 'Bình Địa Mộc', element: 'moc' },
  { name: 'Bích Thượng Thổ', element: 'tho' },
  { name: 'Kim Bạch Kim', element: 'kim' },
  { name: 'Phúc Đăng Hỏa', element: 'hoa' },
  { name: 'Thiên Hà Thủy', element: 'thuy' },
  { name: 'Đại Trạch Thổ', element: 'tho' },
  { name: 'Thoa Xuyến Kim', element: 'kim' },
  { name: 'Tang Đố Mộc', element: 'moc' },
  { name: 'Đại Khê Thủy', element: 'thuy' },
  { name: 'Sa Trung Thổ', element: 'tho' },
  { name: 'Thiên Thượng Hỏa', element: 'hoa' },
  { name: 'Thạch Lựu Mộc', element: 'moc' },
  { name: 'Đại Hải Thủy', element: 'thuy' },
];
